schema: eve/compose/v2
project: evdocs

registry: "eve"

x-eve:
  defaults:
    hints:
      permission_policy: auto_edit

services:
  docs:
    build:
      context: ./website
    ports: [3000]
    environment:
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/api/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 3
    x-eve:
      ingress:
        public: true
        port: 3000
        alias: docs

environments:
  staging:
    pipeline: deploy

pipelines:
  deploy:
    trigger:
      github:
        event: push
        branch: main
    steps:
      - name: build
        action: { type: build }
      - name: release
        depends_on: [build]
        action: { type: release }
      - name: deploy
        depends_on: [release]
        action: { type: deploy }

workflows:
  sync-docs:
    trigger:
      cron:
        schedule: "0 9 * * *"
    hints:
      permission_policy: auto_edit
    git:
      ref: main
      commit: auto
      push: on_success
    steps:
      - agent:
          prompt: |
            You are the eve-horizon-docs auto-sync agent.

            ## Workspace
            You are running in an Eve job. Your cwd is the evdocs project repo.
            Source access is via the GitHub API — no clone needed.

            ## Setup
            1. Authenticate gh with the injected token:
               ```bash
               echo "${GITHUB_TOKEN}" | gh auth login --with-token
               ```
            2. Load the sync-docs skill from private-skills/sync-docs/

            ## Execute
            3. Run the full sync workflow defined in the skill
            4. The skill will:
               - Read .sync-state.json to find the last synced commit
               - Call gh api repos/incept5/eve-horizon/compare/<last>...main
                 to discover what changed (commits, files, patches)
               - Update affected docs pages (human-readable documentation)
               - Read full source files via gh api when patches are truncated
               - Update .sync-state.json with the new commit hash
            5. If there are no changes, report that docs are up to date
            6. If there are changes, they will be committed and pushed
               automatically by the job's git controls (commit: auto,
               push: on_success)
